# config.yaml
paths:
  data: "../mimic_csvs/"
  model: "~/.aurum/models/mimic_demo_model"
query:
  data: "patients.csv"
  class_attr: "gender"
metam:
  epsilon: 0.05
  theta: 0.90
  uninfo: 0
  num_clusters: 10
  tau: 5
  max_iterations: 10
  max_join_paths: 20
  use_multiprocessing: false
  num_processes: 4  # Adjust based on your system
  tpot:
    generations: 10
    population_size: 50
    cv: 2
    n_jobs: -1
    max_time_mins: 60
    max_eval_time_mins: 5
oracle:
  type: "classification"
output:
  path: "augmented_data.csv"
